name: CI Grader
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set execute permission for run-grader
        run: chmod +x run-grader  # Corrige permissão antes da execução
      - name: Download and run grader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -e grader ]]; then echo "grader already exists" >&2; exit 1; fi
          ./run-grader
